echo ""
echo "         {"
echo "      {   }"
echo "       }_{ __{"
echo "    .-{   }   }-."
echo "   (   }     {   )"
echo "   |\`-.._____..-'|"
echo "   |             ;--."
echo "   |            (__  \\"
echo "   |             | )  )"
echo "   |             |/  /"
echo "   |             /  /"
echo "   |            (  /"
echo "   \             y'"
echo "    \`-.._____..-'"
echo ""
echo "Time for a cup of tea?"
echo ""
