echo "             _____"
echo "          .-'.  ':'-."
echo "        .''::: .:    '."
echo "       /   :::::'      \\"
echo "      ;.    ':' \`       ;"
echo "      |       '..       |"
echo "      ; '      ::::.    ;"
echo "       \       '::::   /"
echo "        '.      :::  .'"
echo "          '-.___'_.-'"
echo "  "
echo "are you ready to change the world?"
echo "  "